$MODEL DRAGOSAT_V2 
# Model name: DRAGOSAT_V2      Analysis case: GEO_HOT
#
  $LOCALS
  # GENCODE DUMMY - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.LOCALS"
#
  $NODES
  # GENCODE NODES - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.NODES"
#
  $CONDUCTORS
  # GENCODE CONDUCTORS - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.CONDUCTORS"
#
  $CONSTANTS
  # GENCODE CONSTANTS - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.CONSTANTS"
#
  $ARRAYS
  # GENCODE ARRAYS - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.ARRAYS"
#
  $SUBROUTINES
  # GENCODE SUBROUTINES - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.SUBROUTINES"
C
  $INITIAL
  # GENCODE BOUNDARY_CONDS - DO NOT REMOVE
  # GENCODE INITIAL - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.INITIAL"
C
  $EXECUTION
C
C Steady State Solution
C
      RELXCA=0.01
      NLOOP=100
C
      CALL SOLVFM
C
C Transient Solution
C
      TIMEND=PERIOD
      DTIMEI=TIMEND/100.0
      OUTINT=TIMEND/10.0
C
      CALL SLCRNC

  $VARIABLES1
  # GENCODE VARIABLES1 - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.VARIABLES1"
C
  $VARIABLES2
  # GENCODE VARIABLES2 - DO NOT REMOVE
    $INCLUDE "C:\Users\i.dragovchev\Desktop\proyectos\DRAGOSAT_V2\TMM\Include\DRAGOSAT_V2.VARIABLES2"
C
  $OUTPUTS
      CALL PRNDTB(' ', 'L, T, QS, QE, QA, QI, C', CURRENT)
C
      CALL DMPTMD(' ', 'NODES, CONDUCTORS, CONSTANTS', CURRENT, ' ')

  # GENCODE OUTPUTS - DO NOT REMOVE
C
$ENDMODEL DRAGOSAT_V2
